In [1]:
import numpy as np
import sys

# The Basics

In [2]:
a = np.array([1 , 2 , 3])
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0 , 8.0 , 7.0] ,[6.0 , 5.0 , 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
c = np.array([1 , 2 , 3] , dtype = 'int16')
print(c)

[1 2 3]


## Get Dimension of numpy arrays

In [8]:
print(a.shape)
print(b.shape)
print(c.shape)

(3,)
(2, 3)
(3,)


## Get Type of numpy arrays

In [9]:
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
int16


## Get Size of numpy arrays of each element

In [11]:
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)

4
8
2


## Get total size of numpy arrays

In [13]:
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)

12
48
6


# Accessing/Changing specific elements , rows , columns , etc

In [15]:
a = np.array([[1 , 2 , 3 , 4 , 5 , 6 , 7] , [8 , 9 , 10 , 11 , 12 , 13 , 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


## Get a specific element [r , c]

In [17]:
a[1 , 5]

13

**From end row/column index starts -1 then previous row/column goes -2 , -3 ...**

In [16]:
a[1 , -2]

13

## Get a specific row

In [18]:
a[0 , :]

array([1, 2, 3, 4, 5, 6, 7])

## Get a specific column

**This prints column 4 i.e index 3 of a**

In [19]:
a[: , 3]

array([ 4, 11])

## Get array of columns with specific steps [startindex : endindex : stepsize]

In [20]:
a[: , 1 : 6 : 2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

Above is columns of index 1 3 5 i.e columns with skip index 2

In [22]:
a[: , 1 : -1 : 2]

array([[ 2,  4,  6],
       [ 9, 11, 13]])

## Change an element at an index in an array

In [23]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a[1 , 5] = 20

In [27]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [28]:
a[: , 2] = [1 , 2]

In [29]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


# 3 D matrix example

In [30]:
b = np.array([[[1 , 2] , [3 , 4]] , [[5 , 6] , [7 , 8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Get specific element 3D matrix

In [31]:
b[: , 1 , :]

array([[3, 4],
       [7, 8]])

## Change elements of 3D array

In [32]:
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
b[: , 1 , :] = [[9 , 9] , [8 , 8]]

In [34]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initialize different types of arrays

## All zeros matrix

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros((4,5,6))

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

## All 1s matrix

In [38]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.ones((4 , 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((4 , 5 ,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

## Any other number full((size) , number)

In [41]:
np.full(5 , 93)

array([93, 93, 93, 93, 93])

In [42]:
np.full((2 , 2) , 154)

array([[154, 154],
       [154, 154]])

## Any other number full_like((size) , number)

This is like the shape of another matrix without specifying dimensions

In [43]:
np.full_like(a.shape , 7)

array([7, 7])

## Random decimal numbers

In [45]:
np.random.rand(4 , 2)

array([[0.76731448, 0.94469795],
       [0.46709757, 0.34457103],
       [0.82451888, 0.27009781],
       [0.61921267, 0.15407192]])

In [48]:
np.random.random_sample(b.shape)

array([[[0.80098101, 0.07231705],
        [0.85893294, 0.24227138]],

       [[0.91492395, 0.50197607],
        [0.19644728, 0.45832603]]])

## Random Integer values

syntax : randint(low = 0 (default) , high , size = (size))

In [51]:
np.random.randint(99 , size = (9 , 9))

array([[92, 46, 70, 32, 13, 87, 29, 96, 27],
       [ 2, 76, 87, 55, 66, 74, 74, 81, 17],
       [26, 45, 93, 19, 78, 65, 21, 30,  5],
       [95, 41, 87, 56, 59,  6, 60, 37, 81],
       [42, 60, 24, 77, 49, 64,  0, 83, 42],
       [32, 50, 75, 28, 93, 13, 53, 86, 24],
       [71, 29, 93, 63, 19, 12, 47, 56, 95],
       [67, 58, 56, 18, 95,  7,  8, 33, 23],
       [ 6, 46, 83, 21, 21, 26, 91, 96, 54]])

In [53]:
np.random.randint(-99 , 99 , size = (5 , 5))

array([[ 21, -22, -17,  29,  23],
       [-19,  60,  88, -76,  18],
       [ 11, -83, -97,  10, -79],
       [-86,  28,  20,   2,  22],
       [-75, -30, -67, -18, -92]])

## Identity matrix

In [54]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

## repeat() function

In [56]:
arr = np.array([[1 , 2 , 3]])
r1 = np.repeat(arr , 3 , axis = 0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [57]:
arr = np.array([[1 , 2 , 3]])
r2 = np.repeat(arr , 3 , axis = 1)
r2

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

# Create a matrix using built in functions 

1 1 1 1 1

1 0 0 0 1

1 0 9 0 1

1 0 0 0 1

1 1 1 1 1 

In [59]:
output = np.ones((5 , 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [60]:
z = np.zeros((3 , 3))
z[1 , 1] = 9

print(z)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [61]:
output[1 : -1 , 1 : -1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Copy numpy arrays by value i.e without reference

In [62]:
a = np.array([1 , 2 , 3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


**See in the above code changes in b wont affect a. If we do b = a , change in b will affect a as well and vice versa**

**b = a is just making b and a point to the same object**

# Mathematics

In [63]:
a = np.array([1 , 2 , 3 , 4])
print(a)

[1 2 3 4]


In [64]:
a = a + 2
print(a)

[3 4 5 6]


In [65]:
a = a - 2
print(a)

[1 2 3 4]


In [66]:
a = a * 2
print(a)

[2 4 6 8]


In [67]:
a = a / 2
print(a)

[1. 2. 3. 4.]


In [68]:
b = np.array([1 , 0 , 1 , 0])
a + b

array([2., 2., 4., 4.])

In [69]:
a ** 2

array([ 1.,  4.,  9., 16.])

## Take sin of values

In [70]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

## Take cos of values

In [71]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [72]:
a = np.ones((2 , 3))
print(a)

b = np.full((3 , 2) , 2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


## Matrix Multiplication

In [73]:
np.matmul(a , b)

array([[6., 6.],
       [6., 6.]])

## Finding Determinant

In [74]:
c = np.identity(3)
np.linalg.det(c)

1.0

 Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

 Determinant
 Trace
 Singular Vector Decomposition
 Eigenvalues
 Matrix Norm
 Inverse
 Etc...

# Statistics

In [75]:
stats = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

## Find max value

In [77]:
np.max(stats , axis = 1)

array([3, 6])

In [83]:
np.max(stats , axis = 0)

array([4, 5, 6])

In [80]:
np.max(stats)

6

## Find min value

In [82]:
np.min(stats , axis = 0)

array([1, 2, 3])

In [78]:
np.min(stats , axis = 1)

array([1, 4])

In [81]:
np.min(stats)

1

## Find sum value

In [84]:
np.sum(stats)

21

In [85]:
np.sum(stats , axis = 0)

array([5, 7, 9])

In [86]:
np.sum(stats , axis = 1)

array([ 6, 15])

# Reorganizing Arrays

In [87]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


## Vertically stacking vectors

In [88]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

## Horizontal  stack

In [89]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

Load Data from File

In [90]:
filedata = np.genfromtxt('../datasets/data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Boolean Masking and Advanced Indexing

In [92]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [91]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [93]:
a = np.array([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9])
a[[1 , 2 , 8]]

array([2, 3, 9])

In [94]:
np.any(filedata > 50 , axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])