In [111]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np   
import pandas as pd 

from sklearn.datasets import load_digits

digits = load_digits()

In [112]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(digits.data , digits.target , test_size = 0.3)

In [113]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [114]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [115]:
rf = RandomForestClassifier(n_estimators = 10)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9314814814814815

In [116]:
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [117]:
for train_index , test_index in kf.split([1 , 2 , 3 , 4 , 5 , 6 , 7 , 8 , 9]) :
   print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [118]:
def get_score(model , X_train , X_test , y_train , y_test) : 
  model.fit(X_train , y_train) 
  return model.score(X_test , y_test)

In [119]:
get_score(LogisticRegression() , X_train , X_test , y_train , y_test)

c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [120]:
get_score(SVC() , X_train , X_test , y_train , y_test)

0.9907407407407407

In [121]:
get_score(RandomForestClassifier() , X_train , X_test , y_train , y_test)

0.9703703703703703

In [122]:
from sklearn.model_selection import StratifiedKFold

In [123]:
folds = StratifiedKFold(n_splits = 3)

In [124]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index , test_index in kf.split(digits.data) :
   X_train , X_test , y_train , y_test = digits.data[train_index] , digits.data[test_index] , digits.target[train_index] , digits.target[test_index]
   
   scores_l.append(get_score(LogisticRegression() , X_train , X_test , y_train , y_test))
   scores_svm.append(get_score(SVC() , X_train , X_test , y_train , y_test))
   scores_rf.append(get_score(RandomForestClassifier() , X_train , X_test , y_train , y_test))

c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

In [125]:
scores_l

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [126]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [127]:
scores_rf

[0.9332220367278798, 0.9515859766277128, 0.9198664440734557]

In [128]:
from sklearn.model_selection import cross_val_score

In [129]:
cross_val_score(LogisticRegression() , digits.data , digits.target)

c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\ateet\miniconda3\envs\minimal_ds\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [130]:
cross_val_score(SVC() , digits.data , digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [131]:
cross_val_score(RandomForestClassifier() , digits.data , digits.target)

array([0.93333333, 0.93333333, 0.9637883 , 0.96935933, 0.91922006])

In [132]:
cross_val_score(RandomForestClassifier(n_estimators = 40) , digits.data , digits.target)

array([0.91944444, 0.91666667, 0.93871866, 0.95543175, 0.90807799])

In [133]:
cross_val_score(RandomForestClassifier(n_estimators = 15) , digits.data , digits.target)

array([0.92777778, 0.90555556, 0.94428969, 0.9275766 , 0.90807799])

In [134]:
cross_val_score(RandomForestClassifier(n_estimators = 60) , digits.data , digits.target)

array([0.93055556, 0.92777778, 0.95543175, 0.96100279, 0.93593315])